### ISSUE TITLE
Pubg lagging after installing it

### ISSUE THREAD

**Issue by CoolVampireHD** [pantsufan/Magisk-Ad-Blocking-Module#12]
When i play pubg using ad blocker it starts to lag too much and freeze (poco x3 pro

**Comment by Xryphon** [comment]
It is likely your phone, not the application, that is causing it. The Snapdragon 700 series is made to game at a decent frame rate, not a stable 60 FPS at maximum settings. It's an ad blocker application that appears to work locally, and it simply replaces/ hides files.

**Comment by CoolVampireHD** [comment]
> It is likely your phone, not the application, that is causing it. The Snapdragon 700 series is made to game at a decent frame rate, not a stable 60 FPS at maximum settings. It's an ad blocker application that appears to work locally, and it simply replaces/ hides files.

When i removed the module it became stable again

**Comment by FightFarewellFearless** [comment]
Well, i have same problem here, i can feel lag on my device while using this module. And it run smoothly if i remove this module

**Comment by FightFarewellFearless** [comment]
> it prolly has nothing to do with it tbh

I think it has. Checking millions of lists could be result to performance problem on some devices ofc

**Comment by kusti420** [comment]
completely smooth for me
