### ISSUE TITLE
Can't open any of the 'sponsored' content on google

### ISSUE THREAD

**Issue by TjeerdvanDijk** [pantsufan/Magisk-Ad-Blocking-Module#13]
So I installed the module and all working good but when om browsing Google often there is 'sponsored' content. You click it but the page won't load.

I tried removing the module but it doesn't solve my issue, my best guess is that you get redirected to a host that is blocked, preventing the you from redirecting.

I added pictures as an example 

![Screenshot_20230131-134829_Google](https://user-images.githubusercontent.com/44869554/215765431-56d66c40-1852-4f35-8ca5-fc2266598d64.png)
![Screenshot_20230131-134817_Chrome](https://user-images.githubusercontent.com/44869554/215765441-96e5f0f4-2421-4de8-9bcd-5be5772b38cf.png)

**Comment by kusti420** [comment]
cause these ad links often contain viruses. look at the changelogs, afaik u can whitelist it if you want
