### ISSUE TITLE
Shows inaccessible 

### ISSUE THREAD

**Issue by akkalaashwanth** [pantsufan/Magisk-Ad-Blocking-Module#14]
![Screenshot_20230308-201903_Termux](https://user-images.githubusercontent.com/122966610/223745036-13afe204-2377-4106-84cd-f82e08929edc.png)
As it shows I cannot use any pack.

**Comment by kusti420** [comment]
maybe you havent set up termux correctly. works fine for me

**Comment by akkalaashwanth** [comment]
Can you share your termux link??

**Comment by kusti420** [comment]
> Can you share your termux link??

just download it from f-droid

**Comment by akkalaashwanth** [comment]
Downloaded 0.118.0 version but still same issue..

**Comment by akkalaashwanth** [comment]
From f-droid

**Comment by kusti420** [comment]
> From f-droid

as i said u probably havent set up termux correctly

**Comment by akkalaashwanth** [comment]
Any tutorial videos..?

**Comment by kusti420** [comment]
> Any tutorial videos..?

no. only documentation https://wiki.termux.com/wiki/Termux-setup-storage

**Comment by akkalaashwanth** [comment]
![Screenshot_20230308-232044_Termux](https://user-images.githubusercontent.com/122966610/223791044-1b4c3c59-c7f6-4bdf-88ee-2608f24cf8a8.png)
Not sure what to do after this..

**Comment by kusti420** [comment]
> ![Screenshot_20230308-232044_Termux](https://user-images.githubusercontent.com/122966610/223791044-1b4c3c59-c7f6-4bdf-88ee-2608f24cf8a8.png) Not sure what to do after this..

see if it works now

**Comment by akkalaashwanth** [comment]
Nope same issue..

**Comment by FightFarewellFearless** [comment]
Hey, i've same problem, and i fixed it using `tsu` command instead of `su`

**Comment by ex-xulfi** [comment]
@akkalaashwanth  Use official `tsu` instead of `su` to fix this.
Install using `pkg install tsu`.

**Comment by macerg** [comment]
I agree, the problem is that the 'hosts' file is missing on the server. Problem started 1st May. See the issue I raised.  #17
