### ISSUE TITLE
Buisness of Magisk, make millions out of it

### ISSUE THREAD

**Issue by AnshuMishra01** [pantsufan/Magisk-Ad-Blocking-Module#27]
Hi I am Anshu Mishra, Currently running 2 startups in India and they are profitable, I am quite interested in doing one with you on Magisk-ad-blocker Application. We can reach a good number of people if you take my business advices, I am ready to be your partner, You handle the tech and I the business, but first we need to talk so here's one of my Linkedin profile [Link](https://www.linkedin.com/in/anshu-mishra023129/) or you can mail me at - [anshum.ug21.ee@nitp.ac.in](mailto:anshum.ug21.ee@nitp.ac.in)

**Comment by paulsommer** [comment]
Before you post your "business offers" here, you'd better learn the basics first, especially the difference between "issues" and "spam".
