### ISSUE TITLE
after 3.8 porn sites have been blocked as a whole

### ISSUE THREAD

**Issue by kusti420** [pantsufan/Magisk-Ad-Blocking-Module#3]
mind unblocking them?

**Comment by pantsufan** [comment]
Since this module is created according to my preference, I will not unblock those sites, but based on your request, I have created a special variant with those sites unlocked.
[BlockAds-vP-Unlocked.zip](https://github.com/pantsufan/Magisk-Ad-Blocking-Module/files/7249917/BlockAds-vP-Unlocked.zip)

**Comment by kusti420** [comment]
ty, would be nice if you made a fork where they wouldnt be blocked
