### ISSUE TITLE
ads arent blocked in MS solitaire

### ISSUE THREAD

**Issue by kusti420** [pantsufan/Magisk-Ad-Blocking-Module#5]

**Comment by pantsufan** [comment]
Check if ads are blocked https://github.com/pantsufan/Magisk-Ad-Blocking-Module/releases/tag/v3.11

**Comment by kusti420** [comment]
nope, still seeing ads :(

**Comment by kusti420** [comment]
still not solved afaik

**Comment by pantsufan** [comment]
Are you using the normal version or unlocked version?

**Comment by pantsufan** [comment]
Try this build
[BlockAds-test.zip](https://github.com/pantsufan/Magisk-Ad-Blocking-Module/files/7798991/BlockAds-test.zip)

**Comment by kusti420** [comment]
> Are you using the normal version or unlocked version?

ive tried both, neither one blocks it

**Comment by kusti420** [comment]
> 

this doesnt block ads in ms solitaire either

**Comment by pantsufan** [comment]
For me it doesn't show any ads

**Comment by kusti420** [comment]
> 

strange

**Comment by pantsufan** [comment]
Can you try using the app

**Comment by kusti420** [comment]
> 

even when using that non root app im seeing ads

**Comment by pantsufan** [comment]
Try the latest release, and let me know, if now the ads are showing or not.
