### ISSUE TITLE
trojan

### ISSUE THREAD

**Issue by udneproject** [pantsufan/Magisk-Ad-Blocking-Module#7]
Microsoft Defender detected this
![Снимок экрана (47)](https://user-images.githubusercontent.com/99596170/165765288-857d62cc-63a8-4343-91d5-d76231de9dd7.png)
:

**Comment by pantsufan** [comment]
Sorry for the late response, @kusti420 the above file is not mine. I don't upload my module on Telegram. @udneproject Microsoft Defender does flag the module, only when it is uncompressed because of host file hijack attacks. I recommend that you guys download the module form this repository only.
