### ISSUE TITLE
Took my root permission

### ISSUE THREAD

**Issue by inacio0196** [pantsufan/Magisk-Ad-Blocking-Module#8]
After installing the module using the magisk app, the module took my root permission from the Redmi Note 10s device Also deleted my recovery twrp

**Comment by kusti420** [comment]
seems impossible

**Comment by ViniciusRed** [comment]
@inacio0196 Do you use custom rom?

**Comment by inacio0196** [comment]
@ViniciusRed no

**Comment by ViniciusRed** [comment]
Strange I use the module and I didn't have this problem

**Comment by Xryphon** [comment]
Root is localized; you can't just "take" it without reflashing the original boot.img that doesn't contain some form superuser.

Considering that you're on a Xiaomi device, did you happen to update OTA? That might have flashed a boot.img without Magisk. 

Correlation doesn't equal causation.
